version: 2.1
jobs:
  mssc-beer-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:  mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn integration-test
    docker:
      - image: openjdk:21-rc-slim
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

workflows:
  mssc-beer-workflow:
    jobs:
      - mssc-beer-build

